imports:
    - { resource: ../parameters/parameters.yml }
    - { resource: framework/framework.yml }
    - { resource: logging/logging.yml }
    - { resource: security/security.yml }
    - { resource: rest_api/rest_api.yml }

